name: C/C++ CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build with Action
        uses: schineaj23/vex-blocks-build@1.0
        with:
          path: "test.v5blocks"
      - name: Build with Action and Directory
        uses: schineaj23/vex-blocks-build@1.0
        with:
          path: "test-directory/test.v5blocks"
